"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const cp=require("child_process");
const {ROOT,ROUND_DIR,WARNING_RE,CONFLICT_RE,CORE_SERVICES,abs,isObject,readJson,syntaxCheck,npmRunReferences}=require("./_round5_common.js");
const VERSION="marion.layers1_28.round5Certification/1.0-service-reliability";
const PACKAGE_ROUND4="node tests/marion/layers_1_28/round4/run_round4_certification.js";
const PACKAGE_ROUND5="node tests/marion/layers_1_28/round5/run_round5_certification.js";
const EXPECTED_VERIFY=Object.freeze(["verify:marion-round4","test:marion-round5"]);
const EXPECTED_TESTS=Object.freeze(["round5_1_service_topology_integrity.test.js","round5_2_service_lifecycle_idempotency.test.js","round5_3_fail_closed_resilience.test.js","round5_4_authority_transport_integrity.test.js","round5_5_cross_round_service_cohesion.test.js"]);
const REQUIRED=Object.freeze(["package.json","manifest.json","index.js","tests/marion/layers_1_28/round1/run_round1_certification.js","tests/marion/layers_1_28/round2/run_round2_certification.js","tests/marion/layers_1_28/round3/run_round3_certification.js","tests/marion/layers_1_28/round4/run_round4_certification.js","tests/marion/marionStrategicPlanner.test.js","tests/marion/marionPriorityArbitrator.test.js","tests/marion/marionLayer27Integration.test.js","tests/marion/marionReasoningAuditor.test.js","tests/marion/marionQualityCalibrator.test.js","tests/marion/marionLayer28Integration.test.js","tests/marion/marionLayers27_28Regression.test.js",...CORE_SERVICES,"tests/marion/layers_1_28/round5/_round5_common.js","tests/marion/layers_1_28/round5/round5_certification_manifest.json",...EXPECTED_TESTS.map(n=>`tests/marion/layers_1_28/round5/${n}`)]);
function packageContract(){const pkg=readJson("package.json");assert.ok(isObject(pkg.scripts),"package.json scripts object is missing.");assert.strictEqual(pkg.scripts["test:marion-round4"],PACKAGE_ROUND4,"Round 4 package path drifted.");assert.strictEqual(pkg.scripts["test:marion-round5"],PACKAGE_ROUND5,"Round 5 package path drifted.");const verification=npmRunReferences(pkg.scripts["verify:marion-round5"]);assert.deepStrictEqual(verification,EXPECTED_VERIFY,"verify:marion-round5 must run verify:marion-round4 then test:marion-round5.");assert.strictEqual(pkg.type,"commonjs","CommonJS architecture changed.");assert.ok(isObject(pkg.engines)&&typeof pkg.engines.node==="string"&&pkg.engines.node.trim(),"Node engine declaration is missing.");return{name:String(pkg.name||""),version:String(pkg.version||""),node:pkg.engines.node,verification};}
function requiredFiles(){const missing=REQUIRED.filter(rel=>!fs.existsSync(abs(rel)));assert.deepStrictEqual(missing,[],`Round 5 required files are missing: ${missing.join(", ")}`);}
function manifestContract(){const m=readJson("tests/marion/layers_1_28/round5/round5_certification_manifest.json");assert.strictEqual(m.round,5);assert.strictEqual(m.hardStopLayer,28);assert.strictEqual(m.prerequisite,"verify:marion-round4");const testFiles=Array.isArray(m.tests)?m.tests.map(e=>e&&e.file):[];assert.deepStrictEqual(testFiles,EXPECTED_TESTS,"Round 5 certification manifest does not match the expected five tests.");return m;}
function syntaxChecks(){const js=REQUIRED.filter(rel=>rel.endsWith(".js"));for(const rel of js){const src=fs.readFileSync(abs(rel),"utf8");assert.strictEqual(CONFLICT_RE.test(src),false,`Merge-conflict marker found: ${rel}`);syntaxCheck(abs(rel));}return js;}
function discover(){const d=fs.readdirSync(ROUND_DIR,{withFileTypes:true}).filter(e=>e.isFile()&&e.name.endsWith(".test.js")).map(e=>e.name).sort((a,b)=>a.localeCompare(b));assert.deepStrictEqual(d,[...EXPECTED_TESTS].sort((a,b)=>a.localeCompare(b)),"Round 5 test inventory drifted.");return d;}
function runOne(name){const file=path.join(ROUND_DIR,name);const r=cp.spawnSync(process.execPath,["--trace-warnings","--test",file],{cwd:ROOT,env:{...process.env,NODE_OPTIONS:"",SB_TTS_LOG_ENABLED:"false"},encoding:"utf8",windowsHide:true,timeout:90000,maxBuffer:16*1024*1024});assert.strictEqual(r.error,undefined,r.error&&r.error.message);const output=`${r.stdout||""}\n${r.stderr||""}`;assert.strictEqual(r.status,0,[`Round 5 test failed: ${name}`,output].join("\n"));assert.strictEqual(WARNING_RE.test(output),false,[`Circular warning detected in ${name}`,output].join("\n"));return{file:name,ok:true,warnings:0};}
function main(){const packageProfile=packageContract();requiredFiles();const certificationManifest=manifestContract();const checked=syntaxChecks();const discovered=discover();const executed=discovered.map(runOne);console.log(JSON.stringify({ok:true,certification:"marion-layers-1-28-round5",version:VERSION,title:"Service Reliability and Runtime Cohesion Certification",backendRoot:ROOT,package:packageProfile,prerequisite:"verify:marion-round4",hardStopLayer:28,serviceTopology:CORE_SERVICES,certificationManifest,syntaxChecks:checked,discoveredRound5Tests:discovered,executedRound5Tests:executed,circularWarnings:0,failFast:true},null,2));}
try{main();}catch(e){console.error(e&&e.stack?e.stack:e);process.exitCode=1;}
