"use strict";
const assert=require('assert');
(async()=>{
 const router=require('../Data/marion/runtime/marionIntentRouter.js');
 const composer=require('../Data/marion/runtime/composeMarionResponse.js');
 const envelope=require('../Data/marion/runtime/marionFinalEnvelope.js');
 const bridge=require('../Data/marion/runtime/marionBridge.js');
 const gateway=require('../Data/marion/runtime/MarionAdminConsoleGateway.js');
 const chat=require('../Utils/chatEngine.js');
 const state=require('../Utils/stateSpine.js');
 const prompt='Do a surgical autopsy on the JavaScript law-routing file.';
 const input={prompt,sessionId:'gw',conversationId:'gw',turnId:'gw1',newSession:true,firstTurn:true,isolatedSession:true,passwordFreeTestChat:true,privateAdminConversation:true,directMarionAdminInterface:true,marionAdminConversation:true,adminVerified:true,sessionVerified:true};
 const routed=await router.routeMarionIntent(input);
 assert.strictEqual(routed.routing.domain,'technical');
 const composed=await (composer.composeMarionResponse||composer.run||composer.default)(routed,{...input,routing:routed.routing,marionIntent:routed.marionIntent,privateRuntimeContext:{version:'nyx.marion.privateRuntime/8.0',expectedDomain:'technical',activeDomain:'technical',activeSubject:'JavaScript law-routing file'}});
 assert(composed&&typeof composed==='object');
 assert(/domain precedence|classification boundary|state-commit/i.test(composed.reply||composed.text||''));
 const final=envelope.createMarionFinalEnvelope({...composed,prompt,userText:prompt,rawUserText:prompt,privateAdminConversation:true,directMarionAdminInterface:true,marionAdminConversation:true,privateRuntimeContext:{version:'nyx.marion.privateRuntime/8.0',expectedDomain:'technical',activeDomain:'technical',activeSubject:'JavaScript law-routing file'},routing:routed.routing});
 assert.strictEqual(final.domain,'technical');
 assert(final.reply);
 const bridged=await bridge.processWithMarion(input);
 assert(bridged.reply);
 const unauthorized=await gateway.handleMarionAdminTextRuntime({prompt:'Hello Marion.'},{});
 assert.strictEqual(unauthorized.statusCode,401);
 const gw=await gateway.handleMarionAdminTextRuntime(input,{adminVerified:true,sessionVerified:true,sessionId:'gw'});
 assert.strictEqual(gw.ok,true);
 assert(gw.reply);
 assert.strictEqual(gateway.MARION_UNIFIED_PRIVATE_RUNTIME_GATEWAY_VERSION,'nyx.marion.privateRuntime.gateway/8.0');
 assert.strictEqual(chat.MARION_UNIFIED_PRIVATE_RUNTIME_CONTRACT,'nyx.marion.privateRuntime/8.0');
 assert.strictEqual(state.MARION_UNIFIED_PRIVATE_RUNTIME_STATE_CONTRACT,'nyx.marion.privateRuntime.state/8.0');
 console.log(JSON.stringify({ok:true,routerDomain:routed.routing.domain,composerReply:composed.reply,finalDomain:final.domain,bridgeReply:bridged.reply,gatewayReply:gw.reply,bridgeVersion:bridge.VERSION,unauthorizedStage:unauthorized.stage,adapterStatus:gateway.getPrivateRuntimeAdapterStatus()},null,2));
})().catch(e=>{console.error(e&&e.stack||e);process.exit(1)});
