"use strict";
const assert = require("assert");
const lock = require("../../Data/marion/runtime/publicSurfaceIdentityLock.js");
assert.strictEqual(lock.sanitizePublicReply("I’m with you, Mac."), "I’m with you.");
assert(!/Mac/.test(lock.sanitizePublicReply("Good morning, Mac. Marion is connected behind the response path.")));
assert(!/Marion/.test(lock.sanitizePublicReply("Good morning, Mac. Marion is connected behind the response path.")));
const publicContext = {audience:"public", source:"sandblast_channel_widget", ui:{publicSurfaceOnly:true}, client:{site:"sandblast.channel"}};
assert.strictEqual(lock.isPublicSurfaceContext(publicContext), true);
const privateContext = {audience:"operator", authenticatedOperator:true, operatorPersonalization:true, routeScope:"admin_private"};
assert.strictEqual(lock.isPublicSurfaceContext(privateContext), false);
const projected = lock.projectPublicPayload({ok:true, reply:"I’m with you, Mac. Marion can help."}, publicContext);
assert.strictEqual(projected.publicAgent, "Nyx");
assert.strictEqual(projected.operatorPersonalization, false);
assert(!/Mac|Marion/.test(projected.reply));
const normalizer = require("../../Data/marion/runtime/marionCommandNormalizer.js");
const packet = normalizer.normalizeCommand({message:"hello", audience:"public", source:"sandblast_channel_widget", ui:{publicSurfaceOnly:true}});
assert.strictEqual(packet.meta.publicSurfaceIdentityLock, true);
assert.strictEqual(packet.meta.operatorPersonalization, false);
const finalEnvelope = require("../../Data/marion/runtime/marionFinalEnvelope.js");
const env = finalEnvelope.createMarionFinalEnvelope({reply:"I’m with you, Mac. Marion is ready.", audience:"public", source:"sandblast_channel_widget", ui:{publicSurfaceOnly:true}});
assert(!/Mac|Marion/.test(env.reply));
console.log("public surface identity lock regression passed");
