"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const tts = fs.readFileSync(path.join(root, "Utils", "tts.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.js"), "utf8");
assert.ok(tts.includes('SB_TTS_TRANSPORT || "compat-first"'));
assert.ok(tts.includes('return ["raw", "bearer", "token"]'));
assert.ok(tts.includes('tts.js v2.15.0 SYNTH-COMPAT-FIRST'));
assert.ok(tts.includes('successWithoutAudio'));
assert.ok(tts.includes('function _pickAudioScalar'));
assert.ok(tts.includes('transport: "stream-fallback"'));
assert.ok(index.includes('function sendRawTtsJson'));
assert.ok(index.includes('req.sbTtsRoute = true'));
assert.ok(index.includes('return sendRawTtsJson(res, status, normalized)'));
assert.ok(index.includes('transportMode: "compat-first"'));
assert.ok(index.indexOf('"./Utils/tts"') < index.indexOf('"./tts"'));
console.log("PASS static integrity: 11 assertions");
