"use strict";
const VERSION = "knowledgeRuntime v1.0.0 STABLE-SECTIONS";
const DOMAINS = ["psychology","law","finance","english","cybersecurity","ai","strategy","marketing","general"];
function isObj(v) { return !!v && typeof v === "object" && !Array.isArray(v); }
function arr(v) { return Array.isArray(v) ? v : []; }
function safeStr(v) { return v == null ? "" : String(v).trim(); }
function normalizeItem(item, domain) { if (typeof item === "string") { const text = safeStr(item); if (!text) return null; return { title: `${domain}_knowledge`, content: text, source: `knowledge.${domain}`, score: 0.68, tags: [domain, "knowledge"] }; } if (!isObj(item)) return null; const content = safeStr(item.content || item.text || item.body || item.summary || item.note || ""); if (!content) return null; return { title: safeStr(item.title || item.label || `${domain}_knowledge`) || `${domain}_knowledge`, content, source: safeStr(item.source || `knowledge.${domain}`) || `knowledge.${domain}`, score: Number.isFinite(Number(item.score)) ? Number(item.score) : 0.72, tags: Array.isArray(item.tags) ? item.tags.slice(0, 8) : [domain, "knowledge"] }; }
function inferDomainFromQuery(query = "") { const q = safeStr(query).toLowerCase(); if (/(anxious|sad|panic|overwhelmed|emotion|feel)/.test(q)) return "psychology"; if (/(contract|legal|law|liability)/.test(q)) return "law"; if (/(revenue|pricing|margin|finance|loan)/.test(q)) return "finance"; if (/(grammar|rewrite|english|copy)/.test(q)) return "english"; if (/(breach|malware|security|cyber)/.test(q)) return "cybersecurity"; if (/(model|prompt|inference|ai)/.test(q)) return "ai"; if (/(strategy|roadmap|scale|plan)/.test(q)) return "strategy"; if (/(campaign|brand|marketing)/.test(q)) return "marketing"; return "general"; }
function extract(query = "", opts = {}) { const sections = {}; for (const domain of DOMAINS) sections[domain] = []; const providedSections = isObj(opts.knowledgeSections) ? opts.knowledgeSections : (isObj(opts.knowledge) ? opts.knowledge : {}); for (const domain of DOMAINS) { for (const item of arr(providedSections[domain])) { const normalized = normalizeItem(item, domain); if (normalized) sections[domain].push(normalized); } } const inferred = inferDomainFromQuery(query); if (!sections[inferred].length && safeStr(query)) sections[inferred].push(normalizeItem({ title: `${inferred}_query_context`, content: safeStr(query), source: "knowledge.query_context", score: 0.64 }, inferred)); if (!sections.general.length && safeStr(query)) sections.general.push(normalizeItem({ title: "general_query_context", content: safeStr(query), source: "knowledge.query_context", score: 0.6 }, "general")); const flat = DOMAINS.reduce((acc, domain) => acc.concat(sections[domain]), []); return { ok: flat.length > 0, loaded: flat.length > 0, source: "knowledgeRuntime.extract", extracted: true, inferredDomain: inferred, knowledgeSections: sections, sections, psychology: sections.psychology, law: sections.law, finance: sections.finance, english: sections.english, cybersecurity: sections.cybersecurity, ai: sections.ai, strategy: sections.strategy, marketing: sections.marketing, general: sections.general }; }
module.exports = { VERSION, extract, retrieve: extract };
