"use strict";

/**
 * Utils/musicKnowledge.js — v2.75 (TOP10 LABEL FIX + TOP100 COMMAND + FOLLOWUPS SHAPE FIX + HARDENED RESOLUTION)
 *
 * Goal (non-negotiable):
 *  - Access music sources 1950–2024, deterministic, no dead-ends, no looping defaults.
 *
 * Key fixes vs v2.74:
 * ✅ TOP10 LABEL FIX:
 *    - Top 10 Store (Data/top10_by_year_v1.json) is a YEAR-END TOP 10 spine.
 *    - It should NOT be labeled “Year-End Hot 100” (that implied Top 100 list).
 *    - Introduces: YEAR_END_TOP10_CHART = "Billboard Year-End Top 10"
 *    - Top10 Store rows are now charted as YEAR_END_TOP10_CHART (not YEAR_END_CHART).
 *
 * ✅ TOP100 COMMAND SUPPORT:
 *    - Parses “top 100 1988”, “hot 100 1988”, “year-end hot 100 1988”.
 *    - Returns Top 100 list (limit 100) from merged Wikipedia Hot 100 ranges when present.
 *
 * ✅ FOLLOWUPS SHAPE FIX:
 *    - Returns `followUps` (plural) everywhere (was `followUp` in some branches).
 *    - This prevents downstream UI/engine mismatch (a real “loophole”).
 *
 * ✅ Store-aware resolver hardened:
 *    - 1950–1959: prefers Year-End Singles spine if present.
 *    - 1960+: Top10 Store implies YEAR_END_TOP10_CHART availability (not Hot 100).
 *    - Year-End Singles never “sticks” outside the 50s.
 *
 * NOTE:
 *  - This module can load multiple sources; actual coverage depends on which JSON files exist.
 *  - It degrades gracefully (never throws, never bricks boot).
 */

const fs = require("fs");
const path = require("path");

// =========================
// Version
// =========================
const MK_VERSION =
  "musicKnowledge v2.75 (Top10 Store labeled Year-End Top 10; Top100 command; followUps shape fixed; resolver hardened)";

// =========================
// Public Range / Charts
// =========================
const PUBLIC_MIN_YEAR = 1950;
const PUBLIC_MAX_YEAR = 2024;

const DEFAULT_CHART = "Billboard Hot 100";

// IMPORTANT:
// - YEAR_END_CHART = “Year-End Hot 100” means the full Top 100 year-end list (rank 1–100).
// - YEAR_END_TOP10_CHART = “Year-End Top 10” means the curated Top 10 store list (rank 1–10).
const YEAR_END_CHART = "Billboard Year-End Hot 100";
const YEAR_END_TOP10_CHART = "Billboard Year-End Top 10";
const YEAR_END_SINGLES_CHART = "Billboard Year-End Singles";

// =========================
// Paths
// =========================
const DATA_DIR_ENV = String(process.env.DATA_DIR || "").trim();

// Main DB candidates (optional; not required for Top 10 store)
const DB_CANDIDATES = [
  "Data/music_moments_v2_layer2_plus500.json",
  "Data/music_moments_v2_layer2_plus1000.json",
  "Data/music_moments_v2_layer2_plus2000.json",
  "Data/music_moments_v2_layer2_enriched.json",
  "Data/music_moments_v2_layer2_filled.json",
  "Data/music_moments_v2_layer2.json",
  "Data/music_moments_v2.json",
  "Data/music_moments.json",
];

// Top 10 store (generated by Scripts/build_top10_by_year_v1.js)
const TOP10_STORE_FILE = "Data/top10_by_year_v1.json";

// Wikipedia datasets (existing + planned drop-ins)
const WIKI_YEAREND_SINGLES_1950_1959 =
  "Data/wikipedia/billboard_yearend_singles_1950_1959.json";

// Year-End Hot 100 ranges (merge any that exist)
const WIKI_YEAREND_HOT100_FILES = [
  "Data/wikipedia/billboard_yearend_hot100_1960_1969.json",
  "Data/wikipedia/billboard_yearend_hot100_1970_2010.json",
  "Data/wikipedia/billboard_yearend_hot100_1976_1979.json",
  "Data/wikipedia/billboard_yearend_hot100_2011_2024.json",
];

// =========================
// Optional dependency: Music Moments layer (safe require)
// =========================
let musicMoments = null;
try {
  // eslint-disable-next-line global-require
  musicMoments = require("./musicMoments");
} catch (_) {
  musicMoments = null;
}

// =========================
// Internal State
// =========================
let DB = null;
let LOADED_FROM = null;
let INDEX_BUILT = false;

const BY_YEAR_CHART = new Map(); // `${year}|${chart}` => moments[]
const STATS = {
  moments: 0,
  yearMin: null,
  yearMax: null,
  charts: [],
  sources: {}, // introspection of what loaded
};

// Authoritative cache for 1950–1959 Year-End Singles
const WIKI_SINGLES_50S_BY_YEAR = new Map();
let WIKI_SINGLES_50S_LOADED = false;
let WIKI_SINGLES_50S_LAST_MTIME_MS = 0;

// Top 10 store cache
let TOP10_STORE = null;
let TOP10_STORE_LOADED = false;
let TOP10_STORE_LAST_MTIME_MS = 0;

// =========================
// Helpers
// =========================
function cleanText(s) {
  return String(s || "").replace(/\s+/g, " ").trim();
}

function cleanField(s) {
  let t = cleanText(s);
  t = t.replace(/^"\s*/g, "").replace(/\s*"$/g, "");
  return cleanText(t);
}

function toInt(x) {
  const s = String(x ?? "").trim();
  if (!s) return null;
  const n = Number(s);
  return Number.isFinite(n) ? n : null;
}

function isYearInRange(y) {
  return Number.isFinite(y) && y >= PUBLIC_MIN_YEAR && y <= PUBLIC_MAX_YEAR;
}

function normalizeChart(raw) {
  const s = cleanText(raw);
  if (!s) return DEFAULT_CHART;

  const c = s.toLowerCase();

  if (
    c === "rpm" ||
    c === "canada rpm" ||
    (c.includes("canada") && c.includes("rpm"))
  ) {
    return "Canada RPM";
  }

  // Explicit Year-End Top 10 label
  if (
    (c.includes("year") && c.includes("end") && c.includes("top") && c.includes("10")) ||
    c === "billboard year-end top 10" ||
    c === "year-end top 10"
  ) {
    return YEAR_END_TOP10_CHART;
  }

  if (
    c.includes("year") &&
    c.includes("end") &&
    (c.includes("single") ||
      c.includes("singles") ||
      c.includes("top 30") ||
      c.includes("top 50"))
  ) {
    return YEAR_END_SINGLES_CHART;
  }

  // Year-End Hot 100 (Top 100 list)
  if (c.includes("year") && c.includes("end")) return YEAR_END_CHART;

  if (c.includes("billboard") || c.includes("hot 100") || c.includes("hot100"))
    return DEFAULT_CHART;

  return s;
}

function resolveRepoPath(rel) {
  if (path.isAbsolute(rel)) return rel;
  if (DATA_DIR_ENV) return path.resolve(DATA_DIR_ENV, rel);
  return path.resolve(__dirname, "..", rel);
}

function safeJsonRead(absPath) {
  try {
    const raw = fs.readFileSync(absPath, "utf8");
    return JSON.parse(raw);
  } catch (_) {
    return null;
  }
}

function safeStatMtimeMs(absPath) {
  try {
    const st = fs.statSync(absPath);
    return st && st.mtimeMs ? st.mtimeMs : 0;
  } catch (_) {
    return 0;
  }
}

function bumpSourceStat(key, delta) {
  STATS.sources = STATS.sources || {};
  STATS.sources[key] = (STATS.sources[key] || 0) + (delta || 0);
}

function coerceRank(m) {
  const raw =
    m.rank ?? m.position ?? m.no ?? m.pos ?? m.number ?? m["no."] ?? m["#"];
  const n = toInt(raw);
  return n && n >= 1 && n <= 100 ? n : null;
}

function normalizeMoment(m) {
  if (!m || typeof m !== "object") return m;

  let artist = cleanField(m.artist);
  let title = cleanField(m.title);

  const year = toInt(m.year);
  const rank = coerceRank(m);

  // Known fix: 1988 #3 George Harrison row normalization
  if (
    year === 1988 &&
    rank === 3 &&
    /^harrison$/i.test(artist) &&
    /\bgot\s+my\s+mind\s+set\s+on\s+you\b/i.test(title)
  ) {
    artist = "George Harrison";
    title = "Got My Mind Set on You";
  }

  m.artist = artist || "Unknown Artist";
  m.title = title || "Unknown Title";
  m.chart = normalizeChart(m.chart);

  if (year != null) m.year = year;
  if (rank != null) m.rank = rank;

  return m;
}

function renumberSequentialByRank(rows, limit) {
  const ranked = (rows || []).filter((m) => m && m.rank != null);
  ranked.sort((a, b) => (a.rank ?? 999) - (b.rank ?? 999));
  const out = ranked.slice(0, Math.max(1, limit || ranked.length));
  for (let i = 0; i < out.length; i++) out[i].rank = i + 1;
  return out;
}

function canonicalPatch(session, extra = {}) {
  const patch = {
    activeMusicChart: session.activeMusicChart || DEFAULT_CHART,
    lastMusicYear: session.lastMusicYear ?? null,
    lastMusicChart:
      session.lastMusicChart || session.activeMusicChart || DEFAULT_CHART,
    ...extra,
  };

  if (!patch.lastMusicYear) delete patch.lastMusicYear;
  if (!patch.lastMusicChart) delete patch.lastMusicChart;

  return patch;
}

function safeFollowUps(list) {
  if (!Array.isArray(list)) return [];
  const out = [];
  const seen = new Set();
  for (const it of list) {
    const s = cleanText(it);
    if (!s) continue;
    if (s.length > 80) continue;
    const k = s.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    out.push(s);
    if (out.length >= 10) break;
  }
  return out;
}

// =========================
// Command Parsing (v2.75)
// =========================
function parseCommand(msg) {
  const t = cleanText(msg).toLowerCase();
  if (!t) return null;

  // "top 100 1988" / "hot 100 1988" / "year-end hot 100 1988"
  let m = t.match(/\b(top\s*100|top100|hot\s*100|year[-\s]*end\s*hot\s*100)\s*(\d{4})\b/);
  if (m) return { kind: "top100", year: Number(m[2]) };

  // "top 100" (no year) => use lastMusicYear
  if (/\b(top\s*100|top100|hot\s*100|year[-\s]*end\s*hot\s*100)\b/.test(t) && !/\d{4}/.test(t)) {
    return { kind: "top100" };
  }

  // "top 10 1988" / "top ten 1988"
  m = t.match(/\btop\s*(10|ten)\s*(\d{4})\b/);
  if (m) return { kind: "top10", year: Number(m[2]) };

  // "top 10" (no year) => use lastMusicYear
  if (/\btop\s*(10|ten)\b/.test(t) && !/\d{4}/.test(t)) return { kind: "top10" };

  // "micro moment 1988" / "micro 1988"
  m = t.match(/\b(micro\s+moment|micro)\s*(\d{4})\b/);
  if (m) return { kind: "micro", year: Number(m[2]) };

  // "story moment 1988" / "story 1988" / "moment 1988"
  m = t.match(/\b(story\s+moment|story|music\s+moment|moment|moments)\s*(\d{4})\b/);
  if (m) return { kind: "story", year: Number(m[2]) };

  if (t === "#1" || t === "1" || t === "number 1") return { kind: "number1" };

  return null;
}

// =========================
// Top 10 Store Cache
// =========================
function loadTop10StoreOnce({ force = false } = {}) {
  const abs = resolveRepoPath(TOP10_STORE_FILE);
  const mtimeMs = safeStatMtimeMs(abs);

  const changedOnDisk =
    mtimeMs &&
    TOP10_STORE_LAST_MTIME_MS &&
    mtimeMs !== TOP10_STORE_LAST_MTIME_MS;

  if (changedOnDisk) {
    console.log(
      `[musicKnowledge] Top10 store changed on disk (mtimeMs=${mtimeMs}); reloading.`
    );
  }

  if (force || changedOnDisk) {
    TOP10_STORE = null;
    TOP10_STORE_LOADED = false;
    TOP10_STORE_LAST_MTIME_MS = 0;
  }

  if (TOP10_STORE_LOADED) return;

  TOP10_STORE_LOADED = true;

  if (!fs.existsSync(abs)) {
    bumpSourceStat("top10_store_missing", 1);
    return;
  }

  TOP10_STORE_LAST_MTIME_MS = mtimeMs || safeStatMtimeMs(abs);

  const doc = safeJsonRead(abs);
  if (!doc || typeof doc !== "object") {
    bumpSourceStat("top10_store_badjson", 1);
    return;
  }

  // Accept:
  //  A) {version:"top10_by_year_v1", years:{ "1964":{...} } }
  //  B) root year-map: { "1964":[...], "1965":[...] } or { "1964":{items:[...]} }
  let yearsNode = null;
  if (cleanText(doc.version) === "top10_by_year_v1" && doc.years) {
    yearsNode = doc.years;
  } else {
    yearsNode = doc;
  }

  if (!yearsNode || typeof yearsNode !== "object") {
    bumpSourceStat("top10_store_badshape", 1);
    return;
  }

  TOP10_STORE = { version: "top10_by_year_v1", years: yearsNode };
  bumpSourceStat("top10_store_loaded", 1);
}

function hasTop10StoreYear(year) {
  loadTop10StoreOnce({ force: false });
  if (!TOP10_STORE || !TOP10_STORE.years) return false;

  const node = TOP10_STORE.years[String(year)];
  if (!node) return false;

  if (Array.isArray(node.items) && node.items.length) return true;
  if (Array.isArray(node) && node.length) return true;
  if (Array.isArray(node.rows) && node.rows.length) return true;

  return false;
}

function getTop10StoreList(year, limit = 10) {
  loadTop10StoreOnce({ force: false });
  if (!TOP10_STORE || !TOP10_STORE.years) return [];

  const ykey = String(year);
  const node = TOP10_STORE.years[ykey];
  if (!node) return [];

  // IMPORTANT: store list is “Year-End Top 10”
  const chart = YEAR_END_TOP10_CHART;
  const yearVal = toInt(node.year) || toInt(year);

  let items = [];
  if (Array.isArray(node.items)) items = node.items;
  else if (Array.isArray(node.rows)) items = node.rows;
  else if (Array.isArray(node)) items = node;

  if (!Array.isArray(items) || !items.length) return [];

  const capped = items.slice(0, Math.max(1, Math.min(limit, 10)));

  return capped.map((it) =>
    normalizeMoment({
      year: yearVal,
      rank: toInt(it.pos ?? it.rank ?? it.position ?? it.no ?? it["#"]),
      title: it.title,
      artist: it.artist,
      chart,
      source: TOP10_STORE_FILE,
    })
  );
}

// =========================
// 50s Singles Cache
// =========================
function loadWikiSingles50sOnce({ force = false } = {}) {
  const abs = resolveRepoPath(WIKI_YEAREND_SINGLES_1950_1959);
  const mtimeMs = safeStatMtimeMs(abs);

  const changedOnDisk =
    mtimeMs &&
    WIKI_SINGLES_50S_LAST_MTIME_MS &&
    mtimeMs !== WIKI_SINGLES_50S_LAST_MTIME_MS;

  if (changedOnDisk) {
    console.log(
      `[musicKnowledge] 50s Singles cache changed on disk (mtimeMs=${mtimeMs}); reloading.`
    );
  }

  if (force || changedOnDisk) {
    WIKI_SINGLES_50S_BY_YEAR.clear();
    WIKI_SINGLES_50S_LOADED = false;
    WIKI_SINGLES_50S_LAST_MTIME_MS = 0;
  }

  if (WIKI_SINGLES_50S_LOADED) return;

  WIKI_SINGLES_50S_LOADED = true;

  for (let y = 1950; y <= 1959; y++) WIKI_SINGLES_50S_BY_YEAR.set(y, []);

  if (!fs.existsSync(abs)) {
    console.warn(`[musicKnowledge] 50s Singles cache file not found: ${abs}`);
    bumpSourceStat("wiki_50s_singles_missing", 1);
    return;
  }

  WIKI_SINGLES_50S_LAST_MTIME_MS = mtimeMs || safeStatMtimeMs(abs);

  const doc = safeJsonRead(abs);
  const rows = Array.isArray(doc?.rows)
    ? doc.rows
    : Array.isArray(doc?.moments)
      ? doc.moments
      : Array.isArray(doc)
        ? doc
        : [];

  let count = 0;

  for (const r of rows) {
    const y = toInt(r.year);
    const rk = toInt(r.rank);
    if (!Number.isFinite(y) || y < 1950 || y > 1959) continue;
    if (!Number.isFinite(rk) || rk <= 0) continue;

    const entry = normalizeMoment({
      year: y,
      rank: rk,
      title: r.title,
      artist: r.artist,
      source: "wikipedia",
      chart: YEAR_END_SINGLES_CHART,
    });

    const arr = WIKI_SINGLES_50S_BY_YEAR.get(y) || [];
    arr.push(entry);
    WIKI_SINGLES_50S_BY_YEAR.set(y, arr);
    count++;
  }

  for (let y = 1950; y <= 1959; y++) {
    const arr = WIKI_SINGLES_50S_BY_YEAR.get(y) || [];
    arr.sort((a, b) => (a.rank ?? 999) - (b.rank ?? 999));
    WIKI_SINGLES_50S_BY_YEAR.set(y, arr);
  }

  bumpSourceStat("wiki_50s_singles_rows", count);
}

function hasWikiSingles50sYear(year) {
  loadWikiSingles50sOnce({ force: false });
  const arr = WIKI_SINGLES_50S_BY_YEAR.get(year);
  return Array.isArray(arr) && arr.length > 0;
}

function ensureWikiSingles50sYear(year) {
  if (hasWikiSingles50sYear(year)) return true;
  loadWikiSingles50sOnce({ force: true });
  return hasWikiSingles50sYear(year);
}

function clearWikiSingles50sCache() {
  WIKI_SINGLES_50S_BY_YEAR.clear();
  WIKI_SINGLES_50S_LOADED = false;
  WIKI_SINGLES_50S_LAST_MTIME_MS = 0;
}

// =========================
// DB Load + Index (Plus Wikipedia merges)
// =========================
function extractRowsFromDoc(doc) {
  if (!doc) return [];
  if (Array.isArray(doc)) return doc;
  if (Array.isArray(doc.rows)) return doc.rows;
  if (Array.isArray(doc.moments)) return doc.moments;
  if (Array.isArray(doc.data)) return doc.data;
  return [];
}

function mergeWikipediaYearEndHot100Files(moments, relFiles) {
  const merged = [];
  const failures = [];
  let mergedTotal = 0;

  for (const rel of relFiles || []) {
    const abs = resolveRepoPath(rel);
    if (!fs.existsSync(abs)) continue;

    try {
      const doc = safeJsonRead(abs);
      const rows = extractRowsFromDoc(doc);
      if (!Array.isArray(rows) || !rows.length) continue;

      let count = 0;

      for (const r of rows) {
        const y = toInt(r.year);
        const rk = toInt(r.rank ?? r.pos ?? r.position ?? r.no ?? r["#"]);
        if (!y || !rk) continue;

        merged.push(
          normalizeMoment({
            year: y,
            rank: rk,
            artist: r.artist,
            title: r.title,
            chart: YEAR_END_CHART,
            source: abs,
          })
        );
        count++;
      }

      mergedTotal += count;
      bumpSourceStat("wiki_yearend_hot100_rows", count);

      console.log(
        `[musicKnowledge] Wikipedia Year-End Hot 100 merge: source=${abs} rows=${count}`
      );
    } catch (e) {
      failures.push({ file: abs, error: e?.message || String(e) });
      bumpSourceStat("wiki_yearend_hot100_failures", 1);
    }
  }

  if (failures.length) {
    console.warn(
      `[musicKnowledge] Wikipedia Year-End Hot 100 merge failures: ${JSON.stringify(
        failures
      )}`
    );
  }

  if (!mergedTotal) return moments;
  return moments.concat(merged);
}

function loadDb() {
  if (DB && INDEX_BUILT) return DB;

  // Load caches early
  loadTop10StoreOnce({ force: false });
  loadWikiSingles50sOnce({ force: false });

  let moments = [];
  LOADED_FROM = null;

  for (const rel of DB_CANDIDATES) {
    const abs = resolveRepoPath(rel);
    if (!fs.existsSync(abs)) continue;

    const json = safeJsonRead(abs);
    const rows = extractRowsFromDoc(json);
    if (!Array.isArray(rows) || !rows.length) continue;

    moments = rows;
    LOADED_FROM = abs;
    bumpSourceStat("db_loaded_from", 1);
    break;
  }

  // Merge Wikipedia Year-End Hot 100 files (1960–2024 coverage as available)
  moments = mergeWikipediaYearEndHot100Files(moments, WIKI_YEAREND_HOT100_FILES);

  DB = { moments };

  BY_YEAR_CHART.clear();

  let minY = null;
  let maxY = null;
  const charts = new Set();

  for (const raw of moments) {
    const m = normalizeMoment(raw);
    const y = toInt(m.year);
    const rk = toInt(m.rank);
    const c = normalizeChart(m.chart);

    if (!y || !rk || !c) continue;

    minY = minY == null ? y : Math.min(minY, y);
    maxY = maxY == null ? y : Math.max(maxY, y);
    charts.add(c);

    const key = `${y}|${c}`;
    BY_YEAR_CHART.set(key, [...(BY_YEAR_CHART.get(key) || []), m]);
  }

  for (const [k, arr] of BY_YEAR_CHART.entries()) {
    arr.sort((a, b) => (a.rank ?? 999) - (b.rank ?? 999));
    BY_YEAR_CHART.set(k, arr);
  }

  // Ensure 50s Year-End Singles chart is treated as available if present
  if (hasWikiSingles50sYear(1950)) charts.add(YEAR_END_SINGLES_CHART);

  // Ensure store implies YEAR_END_TOP10_CHART availability
  if (TOP10_STORE && hasTop10StoreYear(1960)) charts.add(YEAR_END_TOP10_CHART);

  STATS.moments = moments.length;
  STATS.yearMin = minY;
  STATS.yearMax = maxY;
  STATS.charts = Array.from(charts);

  // Coverage hints
  if (TOP10_STORE) bumpSourceStat("top10_store_years", Object.keys(TOP10_STORE.years || {}).length);
  if (LOADED_FROM) bumpSourceStat("db_file", 1);

  INDEX_BUILT = true;

  console.log(
    `[musicKnowledge] Loaded ${moments.length} moments (${minY ?? "?"}–${maxY ?? "?"})`
  );
  if (LOADED_FROM) console.log(`[musicKnowledge] DB source: ${LOADED_FROM}`);
  console.log(`[musicKnowledge] Charts: ${STATS.charts.join(" | ")}`);
  console.log(`[musicKnowledge] ${MK_VERSION}`);

  return DB;
}

function chartIsAvailable(chart) {
  loadDb();
  const c = normalizeChart(chart);
  if (c === YEAR_END_TOP10_CHART && TOP10_STORE) return true;
  if (c === YEAR_END_SINGLES_CHART && hasWikiSingles50sYear(1950)) return true;
  return STATS.charts.includes(c);
}

function pickBestAvailableChart(preferredList) {
  loadDb();
  for (const raw of preferredList) {
    const c = normalizeChart(raw);
    if (chartIsAvailable(c)) return c;
  }
  return STATS.charts[0] || (TOP10_STORE ? YEAR_END_TOP10_CHART : DEFAULT_CHART);
}

// =========================
// Chart Resolver (store-aware; no sticky dead-ends)
// =========================
function hasAnyRowsForYearOnChart(year, chart) {
  const y = toInt(year);
  const c = normalizeChart(chart || DEFAULT_CHART);
  if (!y) return false;

  // Top10 store: treat as rows on YEAR_END_TOP10_CHART
  if (c === YEAR_END_TOP10_CHART) {
    if (hasTop10StoreYear(y)) return true;
  }

  if (c === YEAR_END_SINGLES_CHART) {
    return y >= 1950 && y <= 1959 && hasWikiSingles50sYear(y);
  }

  loadDb();
  const arr = BY_YEAR_CHART.get(`${y}|${c}`) || [];
  return Array.isArray(arr) && arr.length > 0;
}

/**
 * Resolve chart for a year, preventing “sticky chart” dead-ends.
 * - 1950–1959: prefer Year-End Singles if available; else fall back.
 * - 1960+: if Top10 Store has year, prefer YEAR_END_TOP10_CHART when caller is doing Top10.
 * - Year-End Singles never dead-ends outside 1950–1959.
 * - If requested chart isn't available, fall back through canonical charts.
 */
function resolveChartForYear(year, requestedChart, { preferTop10Store = false } = {}) {
  const y = toInt(year);
  const req = normalizeChart(requestedChart || DEFAULT_CHART);

  // Safety: if no year, just validate chart availability
  if (!y) {
    const c = chartIsAvailable(req)
      ? req
      : pickBestAvailableChart([YEAR_END_TOP10_CHART, YEAR_END_CHART, DEFAULT_CHART]);
    return { ok: true, chart: c, fellBackFrom: c !== req ? req : undefined };
  }

  // 1950–1959: prefer singles if available (canonical 50s spine)
  if (y >= 1950 && y <= 1959) {
    if (chartIsAvailable(YEAR_END_SINGLES_CHART)) {
      return {
        ok: true,
        chart: YEAR_END_SINGLES_CHART,
        fellBackFrom: req !== YEAR_END_SINGLES_CHART ? req : undefined,
      };
    }
    const c = pickBestAvailableChart([YEAR_END_CHART, DEFAULT_CHART, req]);
    return { ok: true, chart: c, fellBackFrom: c !== req ? req : undefined };
  }

  // 1960+: store-aware preference for TOP10 queries
  if (preferTop10Store && hasTop10StoreYear(y)) {
    if (req !== YEAR_END_TOP10_CHART) {
      return { ok: true, chart: YEAR_END_TOP10_CHART, fellBackFrom: req };
    }
    return { ok: true, chart: YEAR_END_TOP10_CHART };
  }

  // Outside 50s: NEVER hard-fail because req is Singles.
  if (req === YEAR_END_SINGLES_CHART) {
    const c = pickBestAvailableChart([YEAR_END_TOP10_CHART, YEAR_END_CHART, DEFAULT_CHART]);
    return { ok: true, chart: c, fellBackFrom: YEAR_END_SINGLES_CHART };
  }

  // Validate availability
  if (!chartIsAvailable(req)) {
    const c = pickBestAvailableChart([YEAR_END_TOP10_CHART, YEAR_END_CHART, DEFAULT_CHART]);
    return { ok: true, chart: c, fellBackFrom: req };
  }

  return { ok: true, chart: req };
}

// Back-compat wrapper
function chooseChartForYear(year, requestedChart) {
  return resolveChartForYear(year, requestedChart);
}

// =========================
// Queries
// =========================
function getTopByYear(year, chart, limit = 10) {
  const y = toInt(year);
  const c = normalizeChart(chart || DEFAULT_CHART);
  if (!y) return [];

  // 1) Top10 Store (preferred for YEAR_END_TOP10_CHART)
  if (c === YEAR_END_TOP10_CHART) {
    const storeList = getTop10StoreList(y, limit);
    if (storeList.length) return renumberSequentialByRank(storeList, limit);
  }

  // 2) Wikipedia 50s Singles
  if (c === YEAR_END_SINGLES_CHART && y >= 1950 && y <= 1959) {
    if (!ensureWikiSingles50sYear(y)) return [];
    const arr = WIKI_SINGLES_50S_BY_YEAR.get(y) || [];
    if (!arr.length) return [];
    return renumberSequentialByRank(arr, Math.min(limit, arr.length));
  }

  // 3) DB / merged Wikipedia Year-End Hot 100 (and any other chart rows)
  loadDb();
  const arr = BY_YEAR_CHART.get(`${y}|${c}`) || [];
  if (!arr.length) return [];
  return arr.slice(0, Math.min(limit, arr.length));
}

function formatTopList(year, chart, limit = 10) {
  const c = normalizeChart(chart);
  const list = getTopByYear(year, c, limit);
  if (!list.length) return null;

  const lines = list.map((m, i) => {
    const rk = m.rank != null ? String(m.rank) : String(i + 1);
    const a = cleanText(m.artist) || "Unknown Artist";
    const t = cleanText(m.title) || "Unknown Title";
    return `${rk}. ${a} — ${t}`;
  });

  return `Top ${Math.min(limit, lines.length)} — ${c} (${year}):\n${lines.join("\n")}`;
}

function formatTopListWithFallbacks(year, requestedChart, limit = 10) {
  loadDb();
  const y = toInt(year);
  if (!y) return null;

  const wantTop10 = limit <= 10;

  // (A) 1960+: if Top10 Store has year and caller is doing Top10, use YEAR_END_TOP10_CHART
  if (wantTop10 && y >= 1960 && hasTop10StoreYear(y)) {
    const formattedStore = formatTopList(y, YEAR_END_TOP10_CHART, limit);
    if (formattedStore) return { formatted: formattedStore, chartUsed: YEAR_END_TOP10_CHART };
  }

  // (B) 1950–1959: try Singles first
  if (wantTop10 && y >= 1950 && y <= 1959) {
    const formatted50s = formatTopList(y, YEAR_END_SINGLES_CHART, limit);
    if (formatted50s) return { formatted: formatted50s, chartUsed: YEAR_END_SINGLES_CHART };
  }

  const first = normalizeChart(requestedChart);
  const preferred = wantTop10
    ? [first, YEAR_END_TOP10_CHART, DEFAULT_CHART, YEAR_END_CHART]
    : [first, YEAR_END_CHART, DEFAULT_CHART];

  const tryCharts = [];
  for (const c0 of preferred) {
    const c = normalizeChart(c0);
    if (!tryCharts.includes(c) && chartIsAvailable(c)) tryCharts.push(c);
  }

  if (!tryCharts.length && STATS.charts.length) tryCharts.push(STATS.charts[0]);
  if (!tryCharts.length && TOP10_STORE) tryCharts.push(wantTop10 ? YEAR_END_TOP10_CHART : YEAR_END_CHART);

  for (const c of tryCharts) {
    const formatted = formatTopList(y, c, limit);
    if (formatted) return { formatted, chartUsed: c };
  }

  return null;
}

function getNumberOneLine(year, chart) {
  const y = toInt(year);
  const c = normalizeChart(chart || DEFAULT_CHART);
  if (!y) return null;

  // Prefer store for #1 lines when store covers year (via YEAR_END_TOP10_CHART)
  if (c === YEAR_END_TOP10_CHART && hasTop10StoreYear(y)) {
    const list = getTop10StoreList(y, 1);
    if (list.length) {
      const m = list[0];
      const a = cleanText(m.artist) || "Unknown Artist";
      const t = cleanText(m.title) || "Unknown Title";
      return `#1 — ${a} — ${t}`;
    }
  }

  const list = getTopByYear(y, c, 1);
  if (!list.length) return null;

  const m = list[0];
  const a = cleanText(m.artist) || "Unknown Artist";
  const t = cleanText(m.title) || "Unknown Title";
  return `#1 — ${a} — ${t}`;
}

// =========================
// Moments (story/micro): try musicMoments, else deterministic fallback
// =========================
function getMomentFromLayer({ year, chart, kind }) {
  if (!musicMoments) return null;

  try {
    // 1) Preferred: musicMoments.getMoment(...)
    if (typeof musicMoments.getMoment === "function") {
      const res =
        musicMoments.getMoment.length >= 2
          ? musicMoments.getMoment(year, chart, kind)
          : musicMoments.getMoment({ year, chart, kind });

      if (typeof res === "string" && res.trim()) return res.trim();
      if (res && typeof res.text === "string" && res.text.trim()) return res.text.trim();
    }

    // 2) Alternate: musicMoments.handle(...)
    if (typeof musicMoments.handle === "function") {
      const prompt = kind === "micro" ? `micro moment ${year}` : `story moment ${year}`;
      const out = musicMoments.handle(prompt, { activeMusicChart: chart });
      if (out && typeof out.reply === "string" && out.reply.trim()) return out.reply.trim();
    }

    return null;
  } catch (_) {
    return null;
  }
}

function buildDeterministicMoment({ year, chart, kind }) {
  const y = toInt(year);
  const c = normalizeChart(chart || DEFAULT_CHART);

  const top3 = getTopByYear(y, c, 3);
  const top1 = top3[0] || null;
  if (!top1) return null;

  const a1 = cleanText(top1.artist) || "Unknown Artist";
  const t1 = cleanText(top1.title) || "Unknown Title";

  const a2 = top3[1] ? cleanText(top3[1].artist) || "Unknown Artist" : null;
  const t2 = top3[1] ? cleanText(top3[1].title) || "Unknown Title" : null;

  const a3 = top3[2] ? cleanText(top3[2].artist) || "Unknown Artist" : null;
  const t3 = top3[2] ? cleanText(top3[2].title) || "Unknown Title" : null;

  if (kind === "micro") {
    const extra =
      a2 && t2
        ? ` Behind it: ${a2} (“${t2}”).`
        : a3 && t3
          ? ` Close contenders included ${a3} (“${t3}”).`
          : "";

    return (
      `Micro moment — ${y}: On ${c}, #1 was ${a1} with “${t1}.”` +
      extra +
      ` Want the full Top 10, a story moment, or the next year?`
    );
  }

  const spine =
    a2 && t2 && a3 && t3
      ? `The top three shaped the year: ${a1} (“${t1}”), ${a2} (“${t2}”), and ${a3} (“${t3}”).`
      : a2 && t2
        ? `The top of the chart held steady: ${a1} (“${t1}”) with ${a2} (“${t2}”) close behind.`
        : `The year’s defining #1 was ${a1} with “${t1}.”`;

  return (
    `Story moment — ${y}: ${spine} ` +
    `That’s the chart spine; the deeper broadcast story expands as we fill Music Moments. ` +
    `Want Top 10, a micro moment, or another year?`
  );
}

function getMomentOrFallback({ year, chart, kind }) {
  const y = toInt(year);
  if (!isYearInRange(y)) return null;

  const c = normalizeChart(chart || DEFAULT_CHART);

  const fromLayer = getMomentFromLayer({ year: y, chart: c, kind });
  if (fromLayer) return fromLayer;

  return buildDeterministicMoment({ year: y, chart: c, kind });
}

// =========================
// Conversational Entry
// =========================
function handleChat({ text, session }) {
  const msg = cleanText(text);
  session = session || {};

  if (!session.activeMusicChart) session.activeMusicChart = DEFAULT_CHART;

  // Ensure caches are ready (safe/no-op if absent)
  loadTop10StoreOnce({ force: false });
  loadWikiSingles50sOnce({ force: false });

  const cmd = parseCommand(msg);

  // ---- TOP10 ----
  if (cmd && cmd.kind === "top10") {
    const impliedYear = toInt(cmd.year ?? session.lastMusicYear);

    if (!isYearInRange(impliedYear)) {
      return {
        reply: `Give me a year between ${PUBLIC_MIN_YEAR} and ${PUBLIC_MAX_YEAR} (example: “top 10 1988”).`,
        followUps: safeFollowUps(["1956", "1984", "top 10 1988"]),
        domain: "music",
        sessionPatch: canonicalPatch(session),
      };
    }

    const y = impliedYear;

    // Resolve chart for Top10: prefer store chart if available
    const choice = resolveChartForYear(y, session.activeMusicChart, { preferTop10Store: true });
    const chart = choice.chart;

    const out = formatTopListWithFallbacks(y, chart, 10);

    if (out && out.formatted) {
      const used = out.chartUsed || chart;
      return {
        reply: `${out.formatted}\n\nWant #1, a story moment, a micro moment, or another year?`,
        followUps: safeFollowUps(["#1", `story moment ${y}`, `micro moment ${y}`, "Another year", "Next year"]),
        domain: "music",
        sessionPatch: canonicalPatch(session, {
          activeMusicChart: used,
          lastMusicYear: y,
          lastMusicChart: used,
        }),
      };
    }

    const missingHint =
      STATS.moments > 0 || TOP10_STORE ? "" : " (No chart datasets are currently loaded on the server.)";

    return {
      reply:
        `I don’t have a clean Top 10 list for ${y} on the loaded sources in this build yet${missingHint}. ` +
        `I *can* still do a story moment or micro moment for ${y} if you want.`,
      followUps: safeFollowUps([`story moment ${y}`, `micro moment ${y}`, "Another year"]),
      domain: "music",
      sessionPatch: canonicalPatch(session, {
        activeMusicChart: normalizeChart(session.activeMusicChart),
        lastMusicYear: y,
        lastMusicChart: normalizeChart(session.activeMusicChart),
      }),
    };
  }

  // ---- TOP100 ----
  if (cmd && cmd.kind === "top100") {
    const impliedYear = toInt(cmd.year ?? session.lastMusicYear);

    if (!isYearInRange(impliedYear)) {
      return {
        reply: `Give me a year between ${PUBLIC_MIN_YEAR} and ${PUBLIC_MAX_YEAR} (example: “top 100 1988”).`,
        followUps: safeFollowUps(["1988", "top 100 1988", "top 10 1988"]),
        domain: "music",
        sessionPatch: canonicalPatch(session),
      };
    }

    const y = impliedYear;

    // Top100 is explicitly the Year-End Hot 100 list
    const chart = YEAR_END_CHART;
    const out = formatTopListWithFallbacks(y, chart, 100);

    if (out && out.formatted) {
      const used = out.chartUsed || chart;
      return {
        reply: `${out.formatted}\n\nWant the Top 10, #1, a story moment, or another year?`,
        followUps: safeFollowUps([`top 10 ${y}`, "#1", `story moment ${y}`, "Another year"]),
        domain: "music",
        sessionPatch: canonicalPatch(session, {
          activeMusicChart: used,
          lastMusicYear: y,
          lastMusicChart: used,
        }),
      };
    }

    return {
      reply:
        `I don’t have a full Year-End Hot 100 list for ${y} loaded in this build yet. ` +
        `Try “top 10 ${y}”, “#1”, or a story/micro moment.`,
      followUps: safeFollowUps([`top 10 ${y}`, "#1", `story moment ${y}`, `micro moment ${y}`]),
      domain: "music",
      sessionPatch: canonicalPatch(session, {
        activeMusicChart: YEAR_END_CHART,
        lastMusicYear: y,
        lastMusicChart: YEAR_END_CHART,
      }),
    };
  }

  // ---- NUMBER1 ----
  if (cmd && cmd.kind === "number1") {
    const y = toInt(session.lastMusicYear);
    const chart = normalizeChart(session.lastMusicChart || session.activeMusicChart);

    if (!isYearInRange(y)) {
      return {
        reply: `Tell me a year first (example: “1988” or “top 10 1988”), then I can give you #1.`,
        followUps: safeFollowUps(["1988", "top 10 1988", "1956"]),
        domain: "music",
        sessionPatch: canonicalPatch(session),
      };
    }

    // If stored chart is Singles outside 50s, resolve away from it.
    const resolved = resolveChartForYear(y, chart, { preferTop10Store: true });
    const chartUsed = resolved.chart;

    const line = getNumberOneLine(y, chartUsed);
    if (!line) {
      return {
        reply:
          `I can’t pull a clean #1 for ${y} on ${chartUsed} in this build yet. ` +
          `Try “top 10 ${y}”, or ask for a story/micro moment.`,
        followUps: safeFollowUps([`top 10 ${y}`, `story moment ${y}`, `micro moment ${y}`]),
        domain: "music",
        sessionPatch: canonicalPatch(session, {
          activeMusicChart: chartUsed,
          lastMusicYear: y,
          lastMusicChart: chartUsed,
        }),
      };
    }

    return {
      reply: `${line}\n\nWant a story moment, a micro moment, or another year?`,
      followUps: safeFollowUps([`story moment ${y}`, `micro moment ${y}`, "Another year"]),
      domain: "music",
      sessionPatch: canonicalPatch(session, {
        activeMusicChart: chartUsed,
        lastMusicYear: y,
        lastMusicChart: chartUsed,
      }),
    };
  }

  // ---- STORY / MICRO ----
  if (cmd && (cmd.kind === "story" || cmd.kind === "micro")) {
    const y = toInt(cmd.year);
    if (!isYearInRange(y)) {
      return {
        reply: `Give me a year between ${PUBLIC_MIN_YEAR} and ${PUBLIC_MAX_YEAR} for a ${
          cmd.kind === "micro" ? "micro moment" : "story moment"
        }.`,
        followUps: safeFollowUps(["1957", "1988", "1999"]),
        domain: "music",
        sessionPatch: canonicalPatch(session),
      };
    }

    // For moments, we do NOT force the Year-End Top 10 label; we resolve safely.
    const choice = resolveChartForYear(y, session.activeMusicChart, { preferTop10Store: true });
    const chart = choice.chart;

    const moment = getMomentOrFallback({
      year: y,
      chart,
      kind: cmd.kind === "micro" ? "micro" : "story",
    });

    if (!moment) {
      return {
        reply:
          `I can’t pull a clean ${cmd.kind === "micro" ? "micro" : "story"} moment for ${y} on ${chart} in this build yet. ` +
          `Try “top 10 ${y}” or pick another year.`,
        followUps: safeFollowUps([`top 10 ${y}`, "#1", "Another year"]),
        domain: "music",
        sessionPatch: canonicalPatch(session, {
          activeMusicChart: chart,
          lastMusicYear: y,
          lastMusicChart: chart,
        }),
      };
    }

    return {
      reply: moment,
      followUps: safeFollowUps([`top 10 ${y}`, "#1", y + 1 <= PUBLIC_MAX_YEAR ? String(y + 1) : "Another year"]),
      domain: "music",
      sessionPatch: canonicalPatch(session, {
        activeMusicChart: chart,
        lastMusicYear: y,
        lastMusicChart: chart,
      }),
    };
  }

  // Year-only input?
  const yOnly = toInt(msg);
  if (isYearInRange(yOnly)) {
    const y = yOnly;

    // For bare-year, we try Top10 first (store-aware), but label correctly.
    const choice = resolveChartForYear(y, session.activeMusicChart, { preferTop10Store: true });
    const chart = choice.chart;

    const out = formatTopListWithFallbacks(y, chart, 10);

    if (out && out.formatted) {
      const used = out.chartUsed || chart;
      return {
        reply: `${out.formatted}\n\nWant #1, a story moment, a micro moment, or another year?`,
        followUps: safeFollowUps(["#1", `story moment ${y}`, `micro moment ${y}`, "Another year"]),
        domain: "music",
        sessionPatch: canonicalPatch(session, {
          activeMusicChart: used,
          lastMusicYear: y,
          lastMusicChart: used,
        }),
      };
    }

    // No clean top list: offer story/micro (layer or deterministic if possible)
    const story = getMomentOrFallback({ year: y, chart, kind: "story" });
    const micro = getMomentOrFallback({ year: y, chart, kind: "micro" });

    if (micro || story) {
      const reply = micro || story;
      return {
        reply,
        followUps: safeFollowUps([`top 10 ${y}`, "#1", "Another year"]),
        domain: "music",
        sessionPatch: canonicalPatch(session, {
          activeMusicChart: chart,
          lastMusicYear: y,
          lastMusicChart: chart,
        }),
      };
    }

    const missingHint =
      STATS.moments > 0 || TOP10_STORE ? "" : " (No chart datasets are currently loaded on the server.)";

    return {
      reply:
        `I don’t have chart rows loaded for ${y} in this build yet${missingHint}. ` +
        `Try “top 10 ${y}”, or ask for “story moment ${y}” / “micro moment ${y}”.`,
      followUps: safeFollowUps(["1956", `top 10 ${y}`, `story moment ${y}`, `micro moment ${y}`]),
      domain: "music",
      sessionPatch: canonicalPatch(session, {
        activeMusicChart: normalizeChart(session.activeMusicChart),
        lastMusicYear: y,
        lastMusicChart: normalizeChart(session.activeMusicChart),
      }),
    };
  }

  if (/^music$/i.test(msg)) {
    return {
      reply: `Alright—music. Give me a year (1950–2024), or say “top 10 1988”, “top 100 1988”, “story moment 1988”, or “micro moment 1988”.`,
      followUps: safeFollowUps(["1956", "top 10 1988", "top 100 1988", "micro moment 1955"]),
      domain: "music",
      sessionPatch: canonicalPatch(session, { activeMusicChart: DEFAULT_CHART }),
    };
  }

  return {
    reply: `Tell me a year (1950–2024), or say “top 10 1988”, “top 100 1988”, “#1”, “story moment 1988”, or “micro moment 1988”.`,
    followUps: safeFollowUps(["1956", "top 10 1988", "top 100 1988", "story moment 1955"]),
    domain: "music",
    sessionPatch: canonicalPatch(session),
  };
}

// =========================
// Public API
// =========================
module.exports = {
  MK_VERSION: () => MK_VERSION,
  handleChat,
  getStats: () => ({ ...STATS }),
  PUBLIC_RANGE: () => ({ min: PUBLIC_MIN_YEAR, max: PUBLIC_MAX_YEAR }),

  // Ops / debug helpers
  reloadWikiSingles50s: () => loadWikiSingles50sOnce({ force: true }),
  clearWikiSingles50sCache,

  // Store ops (optional)
  reloadTop10Store: () => loadTop10StoreOnce({ force: true }),

  // For diagnostics
  _chartIsAvailable: chartIsAvailable,
  _hasAnyRowsForYearOnChart: hasAnyRowsForYearOnChart,
  _resolveChartForYear: resolveChartForYear,
  _chooseChartForYear: chooseChartForYear,

  // For Utils/musicMoments.js integration (critical)
  _getTopByYear: getTopByYear,
  _getNumberOneLine: getNumberOneLine,
};
